// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfFXKY8cS7w9558ZgL-Q1N5Ry86YgUulE',
    appId: '1:428701699708:web:6a1d24831378e8b5f003f9',
    messagingSenderId: '428701699708',
    projectId: 'uzaar-a8d72',
    authDomain: 'uzaar-a8d72.firebaseapp.com',
    storageBucket: 'uzaar-a8d72.appspot.com',
    measurementId: 'G-3TE05MYRYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCyEUBAKZXuhyhOjZxljkO8WtGZHCY1g',
    appId: '1:428701699708:android:c9a332ea3d487a19f003f9',
    messagingSenderId: '428701699708',
    projectId: 'uzaar-a8d72',
    storageBucket: 'uzaar-a8d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfpFVmpK6mThVJfDcUdMpV6Tqq9s5zDY',
    appId: '1:428701699708:ios:037e9450e8462b2ef003f9',
    messagingSenderId: '428701699708',
    projectId: 'uzaar-a8d72',
    storageBucket: 'uzaar-a8d72.appspot.com',
    iosBundleId: 'com.example.uzaarMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfpFVmpK6mThVJfDcUdMpV6Tqq9s5zDY',
    appId: '1:428701699708:ios:037e9450e8462b2ef003f9',
    messagingSenderId: '428701699708',
    projectId: 'uzaar-a8d72',
    storageBucket: 'uzaar-a8d72.appspot.com',
    iosBundleId: 'com.example.uzaarMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfFXKY8cS7w9558ZgL-Q1N5Ry86YgUulE',
    appId: '1:428701699708:web:e5ce4fe7803b4a4df003f9',
    messagingSenderId: '428701699708',
    projectId: 'uzaar-a8d72',
    authDomain: 'uzaar-a8d72.firebaseapp.com',
    storageBucket: 'uzaar-a8d72.appspot.com',
    measurementId: 'G-JEVY40ZDHH',
  );
}
